# Generated by Django 3.2.8 on 2021-12-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_opera'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opera',
        ),
    ]
